#(C) Copyright 2021 Hewlett Packard Enterprise Development LP
---

# | ----------------------- |
# |  Platform Agent Deploy  |
# | ----------------------- |

- hosts: lab-k8s
  roles:
    - instalacao-basica-k8s

- hosts: lab-k8s-master
  roles:
    - master-k8s

- hosts: lab-k8s-nodes
  vars_files:
   - vars.yaml
  roles:
    - instalacao-nodes
