#(C) Copyright 2021 Hewlett Packard Enterprise Development LP
---
- name: Lista o ultimo arquivo criado
  shell: " ls -lat /home/roney/Documents/ansible-remocao/arquivo* | head -1 | awk '{print $9}' "
  register: lsout
  tags: lsout
  delegate_to: localhost
- debug: msg="{{lsout.stdout}} "

- name: Procurar os arquivos com mais de 3 dias com o modulo find 
  become: yes
  find:
    paths: /home/roney/Documents/ansible-remocao/
    patterns: arquivo_*
    age: 1d
    age_stamp: mtime
  register: files_found
  delegate_to: localhost
- debug: var=item.qualquer
  with_items: "{{ files_found.files }}"

- name: Remove arquivos com o modulo file
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_found.files }}"
  # when: execution_ok == true
  delegate_to: localhost





